import Head from "next/head";
import Hero from "./components/Hero";
import Pliders from "./components/Pliders";
import { SliderData } from "./components/SliderData";




export default function Home() {
  return (
    <div>
       <Head>
        <title>Nero's photos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Hero heading= 'Capture photography' message='I capture all 
     moments and keep them alive'/>
     <Pliders slides={SliderData}/>
     
     
    </div>
     
  );
}
